// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjxHk8Xjqgv0cEIk3NPmIo527d8iw1pIM',
    appId: '1:1051219559868:web:51a53c1ffb4c4e0b4a17b9',
    messagingSenderId: '1051219559868',
    projectId: 'jkb-sept-app',
    authDomain: 'jkb-sept-app.firebaseapp.com',
    storageBucket: 'jkb-sept-app.firebasestorage.app',
    measurementId: 'G-7R3JHJNCTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ-4tMxEcCaUsJmddaSLjwP7M885Pm2UY',
    appId: '1:1051219559868:android:467f41a216f732a14a17b9',
    messagingSenderId: '1051219559868',
    projectId: 'jkb-sept-app',
    storageBucket: 'jkb-sept-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCklYvKU8wBVvLMDg2QpzUgH5jrY-e6itM',
    appId: '1:1051219559868:ios:e07c8c1d27345e544a17b9',
    messagingSenderId: '1051219559868',
    projectId: 'jkb-sept-app',
    storageBucket: 'jkb-sept-app.firebasestorage.app',
    androidClientId:
        '1051219559868-vu9lm5psq3pqd3j8b92pruoqtr014i95.apps.googleusercontent.com',
    iosClientId:
        '1051219559868-rhad8g6rrrvom68mcfq53n3is1cbp8qq.apps.googleusercontent.com',
    iosBundleId: 'com.example.jkbSept',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCklYvKU8wBVvLMDg2QpzUgH5jrY-e6itM',
    appId: '1:1051219559868:ios:e07c8c1d27345e544a17b9',
    messagingSenderId: '1051219559868',
    projectId: 'jkb-sept-app',
    storageBucket: 'jkb-sept-app.firebasestorage.app',
    androidClientId:
        '1051219559868-vu9lm5psq3pqd3j8b92pruoqtr014i95.apps.googleusercontent.com',
    iosClientId:
        '1051219559868-rhad8g6rrrvom68mcfq53n3is1cbp8qq.apps.googleusercontent.com',
    iosBundleId: 'com.example.jkbSept',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjxHk8Xjqgv0cEIk3NPmIo527d8iw1pIM',
    appId: '1:1051219559868:web:56d0d67b372f50934a17b9',
    messagingSenderId: '1051219559868',
    projectId: 'jkb-sept-app',
    authDomain: 'jkb-sept-app.firebaseapp.com',
    storageBucket: 'jkb-sept-app.firebasestorage.app',
    measurementId: 'G-NN2PNGK2JW',
  );
}
